import React from 'react';
import { ArrowLeft, ArrowRight, Check, UserRound } from 'lucide-react';
import { Gender } from '../types';

interface PatientInfoFormProps { patientName: string; setPatientName: (v: string) => void; birthYear: string; setBirthYear: (v: string) => void; address: string; setAddress: (v: string) => void; gender: Gender | null; onSelectGender: (g: Gender) => void; onSubmit: () => void; onBack: () => void; }

export const PatientInfoForm: React.FC<PatientInfoFormProps> = ({ patientName, setPatientName, birthYear, setBirthYear, address, setAddress, gender, onSelectGender, onSubmit, onBack }) => {
  const canSubmit = Boolean(patientName.trim() && birthYear.trim() && gender);
  const fieldClass = 'w-full rounded-xl border border-border bg-background px-4 py-3 text-foreground placeholder:text-muted-foreground transition focus:border-primary focus:bg-card focus:outline-none';
  return <div className="mx-auto flex w-full max-w-2xl flex-1 items-center justify-center py-6"><section className="w-full rounded-[2rem] border border-border bg-card p-6 shadow-lg shadow-primary/5 sm:p-9" aria-labelledby="intake-title">
    <div className="mb-8 flex items-start gap-4"><div className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-primary"><UserRound className="size-6" /></div><div><p className="mb-1 text-xs font-bold uppercase tracking-[0.18em] text-primary">Bước 1 · Thông tin cơ bản</p><h2 id="intake-title" className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Thông tin người được khảo sát</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Thông tin giúp kết quả phù hợp hơn. Các trường có dấu <span className="font-semibold text-red-600">*</span> là bắt buộc.</p></div></div>
    <div className="flex flex-col gap-5"><label className="flex flex-col gap-2 text-sm font-semibold">Họ và tên <span className="text-xs font-normal text-muted-foreground">Bắt buộc</span><input type="text" value={patientName} onChange={e => setPatientName(e.target.value)} className={fieldClass} placeholder="Nhập họ và tên" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="flex flex-col gap-2 text-sm font-semibold">Năm sinh <span className="text-xs font-normal text-muted-foreground">Bắt buộc</span><input type="number" value={birthYear} onChange={e => setBirthYear(e.target.value)} className={fieldClass} placeholder="Ví dụ: 1965" min="1900" max={new Date().getFullYear()} /></label><label className="flex flex-col gap-2 text-sm font-semibold">Địa chỉ <span className="text-xs font-normal text-muted-foreground">Không bắt buộc</span><input type="text" value={address} onChange={e => setAddress(e.target.value)} className={fieldClass} placeholder="Tỉnh / thành phố" /></label></div></div>
    <fieldset className="mt-8"><legend className="mb-3 text-sm font-semibold">Giới tính <span className="text-red-600">*</span></legend><div className="grid gap-3 sm:grid-cols-2">{([['nam','Nam giới'],['nu','Nữ giới']] as const).map(([value, label]) => { const selected = gender === value; return <button key={value} type="button" onClick={() => onSelectGender(value)} aria-pressed={selected} className={`flex items-center justify-between rounded-2xl border p-4 text-left transition ${selected ? 'border-primary bg-primary/10 text-primary shadow-sm' : 'border-border bg-background text-foreground hover:border-primary/50 hover:bg-primary/5'}`}><span className="flex items-center gap-3"><span className={`flex size-10 items-center justify-center rounded-xl ${selected ? 'bg-primary text-primary-foreground' : 'bg-card text-muted-foreground'}`}><UserRound className="size-5" /></span><span className="font-semibold">{label}</span></span>{selected && <Check className="size-5" />}</button>; })}</div></fieldset>
    <div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button onClick={onBack} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold text-muted-foreground transition hover:bg-muted hover:text-foreground"><ArrowLeft className="size-4" /> Quay lại</button><button onClick={onSubmit} disabled={!canSubmit} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 font-semibold text-primary-foreground transition hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-45">Bắt đầu khảo sát <ArrowRight className="size-4" /></button></div>
  </section></div>;
};
