'use client';

import React from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, Check, CircleHelp } from 'lucide-react';
import { Question, ScoreLevel } from '../types';
import { cn } from '../utils';

interface QuizCardProps { question: Question; selectedAnswer?: ScoreLevel; onAnswer: (score: ScoreLevel) => void; onPrevious?: () => void; canGoBack?: boolean; disabled?: boolean; }
const SCORE_LABELS: Record<ScoreLevel, { title: string; desc: string }> = { 1: { title: 'Không có', desc: 'Hoàn toàn không xuất hiện.' }, 2: { title: 'Hiếm khi có', desc: 'Xuất hiện ít trong tuần hoặc tháng.' }, 3: { title: 'Thỉnh thoảng có', desc: 'Xuất hiện đôi khi trong tuần hoặc tháng.' }, 4: { title: 'Thường xuyên có', desc: 'Xuất hiện nhiều ngày trong tuần.' }, 5: { title: 'Luôn luôn có', desc: 'Xuất hiện hầu hết các ngày.' } };

export const QuizCard: React.FC<QuizCardProps> = ({ question, selectedAnswer, onAnswer, onPrevious, canGoBack, disabled }) => <motion.div key={question.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: 0.3 }} className="mx-auto flex w-full max-w-3xl flex-col justify-center py-4">
  <div className="mb-7 flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><CircleHelp className="size-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Câu hỏi {question.id} · Nhóm {question.group}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Dựa trên cảm nhận của cơ thể trong 1 năm gần đây, hãy chọn câu trả lời phù hợp nhất.</p><h3 className="mt-4 text-2xl font-bold leading-tight tracking-tight text-foreground sm:text-3xl">{question.text}</h3></div></div>
  <div className="flex flex-col gap-3">{([1, 2, 3, 4, 5] as ScoreLevel[]).map(score => { const selected = selectedAnswer === score; return <button key={score} type="button" disabled={disabled} aria-pressed={selected} onClick={() => !disabled && onAnswer(score)} className={cn('group flex items-center justify-between gap-4 rounded-2xl border p-4 text-left transition sm:p-5', selected ? 'border-primary bg-primary/10 shadow-sm' : 'border-border bg-card hover:border-primary/50 hover:bg-primary/5', disabled && 'cursor-not-allowed opacity-60')}><span className="flex items-center gap-4"><span className={cn('flex size-10 shrink-0 items-center justify-center rounded-xl font-bold transition', selected ? 'bg-primary text-primary-foreground' : 'bg-muted text-primary group-hover:bg-primary group-hover:text-primary-foreground')}>{score}</span><span className="flex flex-col gap-1"><span className={cn('text-base font-semibold sm:text-lg', selected ? 'text-primary' : 'text-foreground')}>{SCORE_LABELS[score].title}</span><span className="text-xs leading-5 text-muted-foreground sm:text-sm">{SCORE_LABELS[score].desc}</span></span></span>{selected && <Check className="size-5 shrink-0 text-primary" />}</button>; })}</div>
  <button onClick={onPrevious} disabled={!canGoBack || disabled} className="mt-7 inline-flex w-fit items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-muted-foreground transition hover:bg-muted hover:text-foreground disabled:cursor-not-allowed disabled:opacity-40"><ArrowLeft className="size-4" /> Quay lại câu trước</button>
</motion.div>;
