'use client';

import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import type { Schema } from '@/amplify/data/resource';
import outputs from '@/amplify_outputs.json';

// amplify_outputs.json is generated by Amplify deployments. Keep local previews usable
// when the backend has not been deployed yet.
if (Object.keys(outputs).length > 0) {
  Amplify.configure(outputs, { ssr: true });
}

export const dataClient = generateClient<Schema>();
